title: "z3ji"
description: "z3ji's website"
baseurl: "/"
url: "https://z3ji.github.io"

repository: z3ji/z3ji.github.io

github_username: "z3ji"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

highlighter: rouge

source: _src

header_pages:
  - index.md
  #- blog.md

font-size: small
