# site metadata
title: z3ji

repository: z3ji/z3ji.github.io
author: z3ji
description: z3ji's website

# social media usernames
github_username: z3ji

# build settings
url: https://z3ji.github.io
baseurl: "" #/

source: _src

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  #- blog.md

font-size: small
